"""initial

Revision ID: 9476a0af5dcd
Revises:
Create Date: 2023-07-17 01:53:18.014897

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9476a0af5dcd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("language", sa.VARCHAR(), nullable=True),
        sa.Column("latitude", sa.DECIMAL(), nullable=True),
        sa.Column("longitude", sa.DECIMAL(), nullable=True),
        sa.Column("temp_unit", sa.VARCHAR(), nullable=True),
        sa.Column("wind_unit", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
