version: '3.9'

services:

  redis:
    image: redis
    restart: always
    command:
      - redis-server
    ports:
      - 6379:6379
    env_file:
      - .env
    container_name: redis

  mysql:
    image: mysql
    restart: always
    volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
    container_name: mysql


  bot:
    build: .
    restart: always
    command: python bot.py
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    container_name: weather_bot
