"""initial

Revision ID: 9476a0af5dcd
Revises: 
Create Date: 2023-07-17 01:53:18.014897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9476a0af5dcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=2), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('temp_unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('wind_unit', sa.VARCHAR(length=4), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
